config/routes.rb
Rails.application.routes.draw do

resources :password_resets
resources :question_assets, :only => [:index, :new, :create]

  get 'access/login'

  root 'access#login'
  get 'masterreport', to: 'reports#masterreport', as: :report_masterreport
  get 'studentreport', to: 'reports#studentreport', as: :report_studentreport, :via => [ :post]
  get 'chapterreport', to: 'reports#chapterreport', as: :report_chapterreport, :via => [ :post]
  get 'scorereport', to: 'reports#scorereport', as: :report_scorereport, :via => [ :post]

    post 'gamemanagement/save_result/:newResult' => 'gamemanagement#save_result'

match ':controller(/:action(/:id))', :via => [:get, :post]

  

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

before_action :confirm_logged_in

#http://localhost:3000/reports/score?score=1
def score
  begin

      
      if session[:type]== "instructor"

  @score = Score.find(params[:score])
  @students = Student.where(:instructor_id => session[:user_id]).where(:id => @score.student_id)

  if @students.first
    # @score = score_id
    # @students = students
   

   else
     flash[:failure] = "This score belongs to another instructor"
     redirect_to :conrtroller => :reports, :action => :student
   end


else
  @score = Score.find(params[:score])

  @students = Student.where(:id => @score.student_id)
   
end

rescue
   flash[:failure] = "Invalid Score ID"
redirect_to :conrtroller => :reports, :action => :student
end

end

#http://localhost:3000/reports/masterscore
def masterscore
  begin
      
if session[:type] == "instructor"
@students = Student.all.where(:instructor_id => session[:user_id])


  if @students.first
    # @score = score_id
    # @students = students
   else
     flash[:failure] = "This score belongs to another instructor"
     redirect_to :conrtroller => :reports, :action => :student
   end


else

  @students = Student.all
end

rescue
   flash[:failure] = "A problem occured"
redirect_to :conrtroller => :reports, :action => :student
end

end

def chapterscore
  begin
      
      if session[:type]== "instructor"
  @students = Student.all.where(:instructor_id => session[:user_id])
    @chapter = params[:chapter]
    # flash[:success] = @chapter
    # I think this is safe
    @query = 'scores.chapter_id = ' + @chapter

 # @students = @students.where("scores.chapter_id" => @chapter)
 #'scores.chapter_id = 2' 
  @students = @students.joins(:scores).where(@query).distinct

  if @students.first
   else
     flash[:failure] = "No scores"
     redirect_to :conrtroller => :reports, :action => :student
   end


else

  @students = Student.all
      @chapter = params[:chapter]
    # I think this is safe
    @query = 'scores.chapter_id = ' + @chapter

 # @students = @students.where("scores.chapter_id" => @chapter)
 #'scores.chapter_id = 2' 
  @students = @students.joins(:scores).where(@query).distinct
end

rescue
   flash[:failure] = "Invalid Score ID"
redirect_to :conrtroller => :reports, :action => :student
end

end


def studentscore

   begin
      
      if session[:type]== "instructor"
  @students = Student.where(:id => params[:student]).where(:instructor_id => session[:user_id])   


  if @students.first
   else
     flash[:failure] = "No scores"
     redirect_to :conrtroller => :reports, :action => :student
   end


else
  @students = Student.where(:id => params[:student])

end

rescue
   flash[:failure] = "Invalid Score ID"
redirect_to :conrtroller => :reports, :action => :student
end

end
def findscoreid
if(params[:commit] == "View Score Report")
  redirect_to :conrtroller => :reports, :action => :score, :score => params[:score][:score_id]
else



begin

  @score = Score.find(params[:score][:score_id])

  redirect_to report_scorereport_path(format: :csv, :score => @score)
   # respond_to do |format|

   #  format.html{redirect_to root_url}
   #  format.csv{send_data @students.to_csv_masterreport_debug}
   #  end

  rescue
 flash[:failure] = "Invalid Score ID"
redirect_to :conrtroller => :reports, :action => :student
end
  end

end


def scorereport 
  if session[:type]== "instructor"
    # Student.all.where(:instructor_id => session[:user_id])
  @score = Score.find(params[:score])
  @student = Student.where(:instructor_id => session[:user_id]).where(:id => @score.student_id)


if @student.first


  # flash[:success] = @student.first.id
  # @students = @students.joins(:results)
  respond_to do |format|
    format.html{redirect_to :conrtroller => :reports, :action => :student}
    format.csv{send_data @student.to_csv_masterreport}
    # @students.to_csv_with_result
    # format.csv do
    #   headers['Content-Disposition'] = "attachment; filename=\"student-list\""
    #   headers['Content-Type'] ||= 'text/csv'
    # end
  end
  else
     flash[:failure] = "This score belongs to another instructor"
     redirect_to :conrtroller => :reports, :action => :student

    end



  else 
      @score = Score.find(params[:score])

  @student = Student.where(:id => @score.student_id)

   respond_to do |format| 
    #http://localhost:3000/scorereport.csv?

    format.html{redirect_to root_url}
    format.csv{send_data @student.to_csv_masterreport}
end


end

end


def masterreport 
  if session[:type]== "instructor"
    # Student.all.where(:instructor_id => session[:user_id])
  @students = Student.all.where(:instructor_id => session[:user_id])
  # @students = @students.joins(:results)

  respond_to do |format|
    format.html{redirect_to root_url}
    format.csv{send_data @students.to_csv_masterreport}
    # @students.to_csv_with_result
    # format.csv do
    #   headers['Content-Disposition'] = "attachment; filename=\"student-list\""
    #   headers['Content-Type'] ||= 'text/csv'
    # end
  end


  else 
  @students = Student.all

   respond_to do |format|
    format.html{redirect_to root_url}
    format.csv{send_data @students.to_csv_masterreport}
end


end

end

def findchapter

  if(params[:commit] == "View Chapter Report")
  redirect_to :conrtroller => :reports, :action => :chapterscore, :chapter => params[:chapter][:chapter_number]
else
  @chapter = Chapter.find(params[:chapter][:chapter_number])

  redirect_to report_chapterreport_path(format: :csv, :chapter => @chapter)
   # respond_to do |format|

   #  format.html{redirect_to root_url}
   #  format.csv{send_data @students.to_csv_masterreport_debug}
   #  end
 end
  end

def chapterreport
  if session[:type]== "instructor"
    # Student.all.where(:instructor_id => session[:user_id])
  @students = Student.all.where(:instructor_id => session[:user_id])
    @chapter = params[:chapter]
    # I think this is safe
    @query = 'scores.chapter_id = ' + @chapter

 # @students = @students.where("scores.chapter_id" => @chapter)
 #'scores.chapter_id = 2' 
  @students = @students.joins(:scores).where(@query).distinct
  # @students = @students.joins(:results)

  respond_to do |format|
    format.html{redirect_to root_url}
    format.csv{send_data @students.to_csv_masterreport}
    # @students.to_csv_with_result
    # format.csv do
    #   headers['Content-Disposition'] = "attachment; filename=\"student-list\""
    #   headers['Content-Type'] ||= 'text/csv'
    # end
  end


  else 
  @students = Student.all
    @chapter = params[:chapter]
    # I think this is safe
    @query = 'scores.chapter_id = ' + @chapter

 # @students = @students.where("scores.chapter_id" => @chapter)
 #'scores.chapter_id = 2' 
  @students = @students.joins(:scores).where(@query).distinct

   respond_to do |format|
    format.html{redirect_to root_url}
    format.csv{send_data @students.to_csv_masterreport}
end


end

 end

def findstudent
  if(params[:commit] == "View Student Report")
  redirect_to :conrtroller => :reports, :action => :studentscore, :student => params[:student_id][:id]
else

if params[:student_id] != nil
  @student = Student.find(params[:student_id][:id])
end

  if @student == nil
    flash[:failure] = "Please select a student"
    redirect_to :controller => :reports, :action => :student
  else
  redirect_to report_studentreport_path(format: :csv, :student => @student)
end
   # respond_to do |format|

   #  format.html{redirect_to root_url}
   #  format.csv{send_data @students.to_csv_masterreport_debug}
   #  end
 end
  end


def studentreport 
  if session[:type]== "instructor"
    # Student.all.where(:instructor_id => session[:user_id])
  @student = Student.where(:id => params[:student]).where(:instructor_id => session[:user_id])
  # @students = @students.joins(:results)
  respond_to do |format|
    format.html{redirect_to :conrtroller => :reports, :action => :student}
    format.csv{send_data @student.to_csv_masterreport}
    # @students.to_csv_with_result
    # format.csv do
    #   headers['Content-Disposition'] = "attachment; filename=\"student-list\""
    #   headers['Content-Type'] ||= 'text/csv'
    # end
  end


  else 
  @student = Student.where(:id => params[:student])

   respond_to do |format|
    format.html{redirect_to root_url}
    format.csv{send_data @student.to_csv_masterreport}
end


end

end




def download    

@students = Student.all
# find maximum number of children any parent has. Make sure to convert to integer.
@max_children = Result.select('student_id, COUNT(student_id)').group(:student_id).order('COUNT(student_id) DESC').first.count.to_i

@parent_columns = Student.column_names
@child_columns = Result.column_names

@streaming = true
@filename = "download.csv"

respond_to do |format|
   format.html{redirect_to root_url}
  format.csv
end
end


def student_params
      params.permit(:student)
end


def student_params
      params.permit(:score_id)
end


def chapter_params
      params.permit(:chapter).permit(:chapter_number)
end

def vsr_params
      params.permit(:vsr)
end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/chapterscore.html.erb
<% @page_title = "Score" %>
<script type="text/javascript" src="jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="jquery.tablesorter.js"></script> 
<script type="text/javascript">
$(document).ready(function() 
    { 
         $("#myTable").tablesorter( {sortList: [[0,0], [1,0]]} );

    } 
); 
</script>


<h2>Scores</h2>
<table id="myTable" class="tablesorter">
  <thead>
    <tr>
<!--       <th> ID </th>
 -->     <th> Student ID </th>


    
      <th> Active Student? </th>
      <th> Score ID </th>
            <th> Chapter </th>
            <th> Amount Correct </th>
            <th> Amount Possible </th>
             <th> Score </th>

    </tr>
  </thead>
  <tbody>
    <tr>
 <% @students.each do |student| %>
   
<!--       <td><%= student.id %></td>
 -->      <td><strong><%= student.student_id %></strong></td>
      

 <td> <strong><%if student.active == true %>
        <p class="text-success"><%= 'Yes' %></p>
         <% else %>
         <p class="text-danger"><%= 'No' %></p>
         <% end %></strong></td>

<% scores = student.scores.select('*')%>
<% count = 0 %>

<% if scores.first == nil %>
   <td><strong> -- </strong></td>
   <td><strong> -- </strong></td>
   <td><strong> -- </strong></td>
   <td><strong> -- </strong></td>
    <td><strong> -- </strong></td>
<% end %> 

 <% scores.each do |score| %>


<% if count == 0 %>
   <td><strong><%= score.id %></strong></td>
      <td><strong><%= score.chapter_id %></strong></td>
         <td><strong><%= score.is_value %></strong></td>
            <td><strong><%= score.of_value %></strong></td>
                <td><strong><%= score.final_score %> % </strong></td>
<% else %>    
<tr>
<td><strong><%= student.student_id %></strong></td>
      

 <td> <strong><%if student.active == true %>
        <p class="text-success"><%= 'Yes' %></p>
         <% else %>
         <p class="text-danger"><%= 'No' %></p>
         <% end %></strong></td>

   <td><strong><%= score.id %></strong></td>
      <td><strong><%= score.chapter_id %></strong></td>
         <td><strong><%= score.is_value %></strong></td>
            <td><strong><%= score.of_value %></strong></td>
                <td><strong><%= score.final_score %> % </strong></td>
                </tr>
<% end %>  
           <% count = count +1 %>
    
                   
      <% end %>

<% count = 0 %>



   </tr>
    </tr>
    <% end %>
  </tbody>

</table>



<%= link_to("<< Back to  Reports", {:controller => :reports, :action => :student}, :class => "btn btn-primary") %>

app/views/reports/masterscore.html.erb
<% @page_title = "Score" %>
<script type="text/javascript" src="jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="jquery.tablesorter.js"></script> 
<script type="text/javascript">
$(document).ready(function() 
    { 
         $("#myTable").tablesorter( {sortList: [[0,0], [1,0]]} );

    } 
); 
</script>


<h2>Scores</h2>
<table id="myTable" class="tablesorter">
  <thead>
    <tr>
<!--       <th> ID </th>
 -->     <th> Student ID </th>


    
      <th> Active Student? </th>
      <th> Score ID </th>
            <th> Chapter </th>
            <th> Amount Correct </th>
            <th> Amount Possible </th>
             <th> Score </th>

    </tr>
  </thead>
  <tbody>
    <tr>
 <% @students.each do |student| %>
   
<!--       <td><%= student.id %></td>
 -->      <td><strong><%= student.student_id %></strong></td>
      

 <td> <strong><%if student.active == true %>
        <p class="text-success"><%= 'Yes' %></p>
         <% else %>
         <p class="text-danger"><%= 'No' %></p>
         <% end %></strong></td>

<% scores = student.scores.select('*')%>
<% count = 0 %>

<% if scores.first == nil %>
   <td><strong> -- </strong></td>
   <td><strong> -- </strong></td>
   <td><strong> -- </strong></td>
   <td><strong> -- </strong></td>
    <td><strong> -- </strong></td>
<% end %> 

 <% scores.each do |score| %>


<% if count == 0 %>
   <td><strong><%= score.id %></strong></td>
      <td><strong><%= score.chapter_id %></strong></td>
         <td><strong><%= score.is_value %></strong></td>
            <td><strong><%= score.of_value %></strong></td>
                <td><strong><%= score.final_score %> % </strong></td>
<% else %>    
<tr>
<td><strong><%= student.student_id %></strong></td>
      

 <td> <strong><%if student.active == true %>
        <p class="text-success"><%= 'Yes' %></p>
         <% else %>
         <p class="text-danger"><%= 'No' %></p>
         <% end %></strong></td>

   <td><strong><%= score.id %></strong></td>
      <td><strong><%= score.chapter_id %></strong></td>
         <td><strong><%= score.is_value %></strong></td>
            <td><strong><%= score.of_value %></strong></td>
                <td><strong><%= score.final_score %> % </strong></td>
                </tr>
<% end %>  
           <% count = count +1 %>
    
                   
      <% end %>

<% count = 0 %>



   </tr>
    </tr>
    <% end %>
  </tbody>

</table>



<%= link_to("<< Back to  Reports", {:controller => :reports, :action => :student}, :class => "btn btn-primary") %>

app/views/reports/reports.html.erb
<h2>Reports</h2>
<p>
  The time is now: <%= Time.now %>
</p>

<br />
<%= link_to("<< Back to  Menu", {:controller => :menu, :action => :menu}, :class => "btn btn-primary") %>

app/views/reports/score.html.erb
<% @page_title = "Score" %>
<script type="text/javascript" src="jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="jquery.tablesorter.js"></script> 
<script type="text/javascript">
$(document).ready(function() 
    { 
         $("#myTable").tablesorter( {sortList: [[0,0], [1,0]]} );

    } 
); 
</script>


<h2>Score</h2>
<table id="myTable" class="tablesorter">
  <thead>
    <tr>
<!--       <th> ID </th>
 -->     <th> Student ID </th>


    
      <th> Active Student? </th>
      <th> Score ID </th>
            <th> Chapter </th>
            <th> Amount Correct </th>
            <th> Amount Possible </th>
             <th> Score </th>

    </tr>
  </thead>
  <tbody>
    <tr>
 <% @students.each do |student| %>
   
<!--       <td><%= student.id %></td>
 -->      <td><strong><%= student.student_id %></strong></td>
      

 <td> <strong><%if student.active == true %>
        <p class="text-success"><%= 'Yes' %></p>
         <% else %>
         <p class="text-danger"><%= 'No' %></p>
         <% end %></strong></td>

   <td><strong><%= @score.id %></strong></td>
      <td><strong><%= @score.chapter_id %></strong></td>
         <td><strong><%= @score.is_value %></strong></td>
            <td><strong><%= @score.of_value %></strong></td>
                <td><strong><%= @score.final_score %> % </strong></td>




   </tr>
    </tr>

    <% end %>
  </tbody>

</table>



<%= link_to("<< Back to  Menu", {:controller => :menu, :action => :menu}, :class => "btn btn-primary") %>
<%= link_to("<< Back to  Reports", {:controller => :reports, :action => :student}, :class => "btn btn-success") %>

app/views/reports/student.csv.erb
<%- headers = ['Name'] -%>
<%= CSV.generate_line headers %>
<%- @students.each do |student| -%>
<%= CSV.generate_line([student.student_id]) -%>
<%- end -%>

app/views/reports/student.html.erb
<!-- <div class="jumbotron">
 --><h3>Reports</h3>

  <div class="form-group">
      <label for="chapter" class="col-lg-2 control-label"><h4>Score</h4></label>
      <div class="col-lg-10">

      <%= form_for(:score, :url => {:action => 'findscoreid' }) do |f| %>

        <%= f.label("Score Id: " ) %>
        <%= f.text_field(:score_id) %>
<br />

    <br />  

       <%= submit_tag("Download Score Report", :class => "btn btn-warning") %> 
       <%= submit_tag("View Score Report",  :class => "btn btn-warning btn-med") %>

       <br />  
  <% end %> 
      </div>
    </div>


       <br />  



 <div class="form-group">
      <label for="chapter" class="col-lg-2 control-label"><h4>Chapter</h4></label>
      <div class="col-lg-10">

      <%= form_for(:chapter, :url => {:action => 'findchapter'}) do |f| %>

        <%= f.collection_select(:chapter_number, Chapter.all, :id, :number_with_title, {:selected => @chapter_number.to_i}, {:class=>'form-control'}) %>
<br />



       <%= submit_tag("Download Chapter Report", :class => "btn btn-primary") %> 
       <%= submit_tag("View Chapter Report",  :class => "btn btn-primary btn-med") %>

       <br />  
  <% end %> 
      </div>
    </div>


       <br />  

    <div class="form-group">
      <label for="student" class="col-lg-2 control-label"><h4>Student</h4></label>
      <div class="col-lg-10">
<%= form_for(:student, :url => {:action => :findstudent}) do |f| %>
<% if session[:type] == "instructor" %>

<%= collection_select(:student_id, :id, Student.all.where(:instructor_id => session[:user_id], :active => true), :id, :student_id, {}, {:class=>'form-control'}) %>
<%else%>

<%= collection_select(:student_id, :id, Student.all, :id, :student_id, {}, {:class=>'form-control'}) %>
<%end%>



<div class="actions">
<br />  
        <%= submit_tag("Download Student Report", :class => "btn btn-success") %> 
        <%= submit_tag("View Student Report", :class => "btn btn-success") %> 


</div>

      <% end %>


      </div>
    </div>

  <label for="student" class="col-lg-2 control-label">
<!-- <p> -->
<h4>Full Report</h4>
<%= link_to 'Download Full Report', report_masterreport_path(format: :csv), :class => "btn btn-info btn-med" %> <%= link_to("View Full Report", {:controller => :reports, :action => :masterscore}, :class => "btn btn-info btn-med") %>

 </div>

app/views/reports/studentscore.html.erb
<% @page_title = "Score" %>
<script type="text/javascript" src="jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="jquery.tablesorter.js"></script> 
<script type="text/javascript">
$(document).ready(function() 
    { 
         $("#myTable").tablesorter( {sortList: [[0,0], [1,0]]} );

    } 
); 
</script>


<h2>Scores</h2>
<table id="myTable" class="tablesorter">
  <thead>
    <tr>
<!--       <th> ID </th>
 -->     <th> Student ID </th>


    
      <th> Active Student? </th>
      <th> Score ID </th>
            <th> Chapter </th>
            <th> Amount Correct </th>
            <th> Amount Possible </th>
             <th> Score </th>

    </tr>
  </thead>
  <tbody>
    <tr>
 <% @students.each do |student| %>
   
<!--       <td><%= student.id %></td>
 -->      <td><strong><%= student.student_id %></strong></td>
      

 <td> <strong><%if student.active == true %>
        <p class="text-success"><%= 'Yes' %></p>
         <% else %>
         <p class="text-danger"><%= 'No' %></p>
         <% end %></strong></td>

<% scores = student.scores.select('*')%>
<% count = 0 %>

<% if scores.first == nil %>
   <td><strong> -- </strong></td>
   <td><strong> -- </strong></td>
   <td><strong> -- </strong></td>
   <td><strong> -- </strong></td>
    <td><strong> -- </strong></td>
<% end %> 

 <% scores.each do |score| %>


<% if count == 0 %>
   <td><strong><%= score.id %></strong></td>
      <td><strong><%= score.chapter_id %></strong></td>
         <td><strong><%= score.is_value %></strong></td>
            <td><strong><%= score.of_value %></strong></td>
                <td><strong><%= score.final_score %> % </strong></td>
<% else %>    
<tr>
<td><strong><%= student.student_id %></strong></td>
      

 <td> <strong><%if student.active == true %>
        <p class="text-success"><%= 'Yes' %></p>
         <% else %>
         <p class="text-danger"><%= 'No' %></p>
         <% end %></strong></td>

   <td><strong><%= score.id %></strong></td>
      <td><strong><%= score.chapter_id %></strong></td>
         <td><strong><%= score.is_value %></strong></td>
            <td><strong><%= score.of_value %></strong></td>
                <td><strong><%= score.final_score %> % </strong></td>
                </tr>
<% end %>  
           <% count = count +1 %>
    
                   
      <% end %>

<% count = 0 %>



   </tr>
    </tr>
    <% end %>
  </tbody>

</table>



<%= link_to("<< Back to  Reports", {:controller => :reports, :action => :student}, :class => "btn btn-primary") %>